# Generated by Django 5.1.4 on 2024-12-15 10:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gkid', models.CharField(max_length=100, unique=True)),
                ('organizationid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('createDate', models.DateField(default=datetime.date.today)),
                ('latestexamdate', models.DateField(blank=True, null=True)),
                ('total_exam_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'patient_info',
                'indexes': [models.Index(fields=['gkid', 'organizationid'], name='patient_inf_gkid_7ee231_idx'), models.Index(fields=['latestexamdate'], name='patient_inf_lateste_6350d2_idx')],
                'unique_together': {('gkid', 'organizationid')},
            },
        ),
        migrations.CreateModel(
            name='PatientExaminationRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateField(default=django.utils.timezone.now)),
                ('file_url', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_position', models.CharField(blank=True, max_length=10, null=True)),
                ('corneal_topography_right_eye_k1', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_eye_k1_axis', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_eye_k2', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_eye_k2_axis', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_eye_delta_k', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_pinge', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_xiee', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_is', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_sai', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_sri', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_pupil', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_pupil_area', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_hvid', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_tfsq', models.FloatField(blank=True, null=True)),
                ('corneal_topography_right_ctfsq', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_eye_k1', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_eye_k1_axis', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_eye_k2', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_eye_k2_axis', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_eye_delta_k', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_pinge', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_xiee', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_is', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_sai', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_sri', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_pupil', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_pupil_area', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_hvid', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_tfsq', models.FloatField(blank=True, null=True)),
                ('corneal_topography_left_ctfsq', models.FloatField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corneal_topography.pinfo')),
            ],
            options={
                'db_table': 'patient_examination_records',
            },
        ),
        migrations.CreateModel(
            name='PatientReviewReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_review_date', models.DateField()),
                ('review_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corneal_topography.patientexaminationrecords')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corneal_topography.pinfo')),
            ],
            options={
                'db_table': 'patient_review_reminder',
                'indexes': [models.Index(fields=['patient_id', 'review_date'], name='patient_rev_patient_9cd4e2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='patientexaminationrecords',
            index=models.Index(fields=['patient_id', 'examination_date'], name='patient_exa_patient_fbd6de_idx'),
        ),
    ]
